### ISSUE TITLE
Support for Alerting Channels

### ISSUE THREAD

**Issue by ianaya89** [checkly/checkly-cli#58]
## Alert Channels RFC

<img width="1904" alt="Screen Shot 2021-11-11 at 21 43 25" src="https://user-images.githubusercontent.com/3258966/142001669-8f4d6589-99d9-4630-bf24-dcd29adb78cb.png">

- All `alert-channels` should be inside the alert-channels directory (same patterns as `checks`).
- Inside your checks. you can refer to any alert channel using the file name (In this case `email`).
- Parser will check that the alert name used in the check exists as a yml file at `alert-channels` directory. It will also parse the whole `alert-channels` directory (We will allow creating channels that are not linked to any check.)
- When running the sync command, the server will detect the dependencies. So it will first create/update/delete the `alert-channel` and later create/update/delete the check with the corresponding subscriptions

**Comment by tnolet** [comment]
@ianaya89 I have a strong feeling we are playing too much with "magic strings" here. The name of the file represents the alert channel, which we then reference, minus the actual folder name. Also, when life cycling this — for instance changing the file name — you would need careful search & replace as a name like "email" is very generic.

**Comment by ianaya89** [comment]
Yes, I think makes sense. 
So you propose to use the complete file name to link them?
```yml
checkType: API
name: API Check 2
request:
  url: https://google.com
  method: GET
frequency: 10
activated: true
locations:
  - us-east-1
alertChannelSubscriptions:
  - alertChannel: email.yml
    activated: true
```
