### ISSUE TITLE
Support for Assertions

### ISSUE THREAD

**Issue by ianaya89** [checkly/checkly-cli#59]

**Comment by ndom91** [comment]
For assertions, I did some research in the ansible and kubernetes testing space as they're both super heavy yml users, and it seems like most projects do one of two things (in terms of defining assertions in yml):

1. Verbose
```yml
assertions:
  - field: check.responseCode
    action: equals
    value:  200
  - field: check.responseTime
    action: lessThan
    value:  1000
```
2. Terse
```yml
assertions:
  - check.responseCode = 200
  - check.responseTime < 1000
```

Do you have any other ideas on how to define assertions well in yml? If its between those two my vote would be for the terse option. Shouldn't be too difficult to parse either.
