### ISSUE TITLE
docs: examples deploy checks from pull requests before they are merged

### ISSUE THREAD

**Issue by alvarlagerlof** [checkly/checkly-cli#624]
### What is the improvement or update you wish to see?

Currently, the example GitHub actions workflows run on:

```yml
on: [deployment_status]
```

And then they end with these two steps

```yml
  - name: Run checks
        id: run-checks
        run: npm run checkly:test -- -e ENVIRONMENT_URL=${{ env.ENVIRONMENT_URL }}
        continue-on-error: false
      - name: Deploy checks
        if: steps.run-checks.outcome == 'success'
        run: npm run checkly:deploy
```

Focusing on the last step, the deploy, I can see that it will not happen if the `checkly:test` is not sucessfull. That's great, but what seems to will happen is this:

If a new PR is opened, and the `checkly:test` step completes, the `checkly:deploy` will run, overriding whatever checks iare deployed as "prod" to Checkly. I may be wrong here, but if I am not, this seems like a very incorrect setup. Wouldn't you only want to deploy to Checkly when merging to the `main` branch? Otherwise open PRs with sucessfull tests are constantly going to override the "prod" checks on Checkly.

Happy to make a PR fix this. What I've done personally is having two scripts. One that runs on pushes to main, and one that runs for every pull request push, much like the current example. It might also be possible to add an extra `if: ` case to the deploy step, and keep to a single workflow file.

### Is there any context that might help us understand?

I want to treat Checkly similarly to how Vercel works.

### Does the docs page already exist? Please link to it.

https://github.com/checkly/checkly-cli/blob/main/examples/advanced-project/.github/workflow.yml
