### ISSUE TITLE
feat: allow `--reporter=github` output summary with failing checks

### ISSUE THREAD

**Issue by tdeekens** [checkly/checkly-cli#682]
### What problem does this feature solve?

When calling the CLI like `pnpm checkly test --reporter=github --record` the test will fail if a check fails causing the CI workflow to fail. This however, might not always be intended when wanting to use the reporters output for a step summary

Imagine the following setup

```yaml
- name: Running checks
   run: pnpm checkly test --reporter=github --record
   env:
     CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
     CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
 
- name: Create job summary
   id: create-summary
   run: cat checkly-github-report.md > $GITHUB_STEP_SUMMARY
```

I would prefer to get a summary even if a check targeted with the `test` call fails. Currently I worked around it with a `|| true` but it feels not ideal.

### How would you implement this feature?

Not 100% sure if it should be solved or documented as expected behavior. One idea to solve it is to build knowledge into the CLI on which reporter to fail and which not which feels like unwanted coupling. An alternative would be to add a `--fail-on-failed-check` or similar. 

Side note, it might still be desirable that the CI workflow fails it's just that one might even with a failing check wants a summary.

It might also be missing knowledge on my part how the setup is envisioned 🤗.

**Comment by tdeekens** [comment]
To follow up I am experimenting with an improved setup which looks something like

```yaml
- name: Running checks
  # The check test should not fail to generate a summary
  run: |
    pnpm checkly test --reporter=github --record  2> /dev/null
    echo "CHECKLY_EXIT_CODE=$?" >> "$GITHUB_ENV"
  env:
    CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
    CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}

- name: Create job summary
  id: create-summary
  run: cat checkly-github-report.md > $GITHUB_STEP_SUMMARY

- name: Exiting if checks failed
  run: |
    if [ $? -eq 1 ]
    then
      echo "Some Checkly checks have failed." >&2
      exit 1
    fi
```
